# Metadata for the plugin
plugin:
    # Global plugin attributes
    type: gateway                   # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Anbindung eines Foshk Wetterstation-Gateway wie bspw. GW1000 mit entsprechender API'
        en: 'Connect to a Foshk weatherstation gateway like GW1000 using their API'
    maintainer: sisamiwe
#    tester:                         # Who tests this plugin?
    state: develop                   # change to ready when done with development
#    keywords: iot xyz
#    documentation: https://github.com/smarthomeNG/smarthome/wiki/CLI-Plugin        # url of documentation (wiki) page
#    support: https://knx-user-forum.de/forum/supportforen/smarthome-py

    version: 1.0.0                  # Plugin version (must match the version specified in __init__.py)
    sh_minversion: 1.8              # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    py_minversion: 3.8              # minimum Python version to use for this plugin
#    py_maxversion:                 # maximum Python version to use for this plugin (leave empty if latest)
    multi_instance: false           # plugin supports multi instance
    restartable: unknown
    classname: Foshk                # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml (enter 'parameters: NONE', if section should be empty)
            # Server_IP:
                # type: ipv4
                # default: '192.168.2.12'
                # description:
                    # de: 'IP-Adresse des TCP-Servers, auf den das Gateway die Daten sendet'
                    # en: 'IP-Adress of the TCP-Server, where the gateway will send the data to'

            # Server_Port:
                # type: int
                # default: 8070
                # description:
                    # de: 'Port des TCP-Servers, auf den das Gateway die Daten sendet'
                    # en: 'Port of the TCP-Server, where the gateway will send the data to'
                    
            # Cycle:
                # type: int
                # default: 30
                # valid_min: 10
                # valid_max: 600
                # description:
                    # de: 'Zyklus, in dem die Daten vom Server abgeholt werden; (sollte größer sein, als Intervall)'
                    # en: 'Cycle in which the data will put pulled from server'
                    
            # Interval:
                # type: int
                # mandatory: False
                # default: 20
                # valid_min: 16
                # valid_max: 600
                # description:
                    # de: 'Intervall, in dem das Gateway die Daten bereitstellt, bzw. hochläd'
                    # en: 'Interval the gateway provides the data'
            
    Gateway_IP:
        type: ipv4
        mandatory: False
        default: '255.255.255.255'
        description:
            de: 'IP-Adresse des Gateways'
            en: 'IP-Adress of the gateway'
            
    Gateway_Port:
        type: int
        mandatory: False
        default: 45000
        description:
            de: 'UDP Port des Gateways'
            en: 'UDP Port of the Gateway'
            
    Gateway_Poll_Interval:
        type: int
        mandatory: False
        default: 20
        valid_min: 10
        valid_max: 600
        description:
            de: 'Zyklus, in dem die Daten via API abgerufen werden'
            en: 'Cycle in which the data will be pulled via API'

item_attributes:
    foshk_attibute:
        type: str
        description:
            de: 'Datenattribut der Foshk-API'
            en: 'Data attribute of Foshk API'
        valid_list:
            - intemp
            - outtemp
            - dewpoint
            - windchill
            - heatindex
            - inhumid
            - outhumid
            - absbarometer
            - relbarometer
            - light
            - uv
            - uvi
            - datetime
            - temp1
            - temp2
            - temp3
            - temp4
            - temp5
            - temp6
            - temp7
            - temp8
            - temp9
            - temp10
            - temp11
            - temp12
            - temp13
            - temp14
            - temp15
            - temp16
            - temp17
            - humid1
            - humid2
            - humid3
            - humid4
            - humid5
            - humid6
            - humid7
            - humid8
            - humid17
            - leafwet1
            - leafwet2
            - leafwet3
            - leafwet4
            - leafwet5
            - leafwet6
            - leafwet7
            - leafwet8
            - pm251
            - pm252
            - pm253
            - pm254
            - pm255
            - pm10
            - co2
            - soiltemp1
            - soilmoist1
            - soiltemp2
            - soilmoist2
            - soiltemp3
            - soilmoist3
            - soiltemp4
            - soilmoist4
            - soiltemp5
            - soilmoist5
            - soiltemp6
            - soilmoist6
            - soiltemp7
            - soilmoist7
            - soiltemp8
            - soilmoist8
            - soiltemp9
            - soilmoist9
            - soiltemp10
            - soilmoist10
            - soiltemp11
            - soilmoist11
            - soiltemp12
            - soilmoist12
            - soiltemp13
            - soilmoist13
            - soiltemp14
            - soilmoist14
            - soiltemp15
            - soilmoist15
            - soiltemp16
            - soilmoist16
            - pm251_24h_avg
            - pm252_24h_avg
            - pm253_24h_avg
            - pm254_24h_avg
            - pm255_24h_avg
            - pm10_24h_avg
            - co2_24h_avg
            - leak1
            - leak2
            - leak3
            - leak4
            - lightningdist
            - lightningdettime
            - lightningcount
            - lightning_strike_count
            # rain
            - rain
            - rainevent
            - rainrate
            - rainhour
            - rainday
            - rainweek
            - rainmonth
            - rainyear
            - raintotals
            # wind
            - winddir
            - windspeed
            - gustspeed
            - daymaxwind
            # battery
            - wh40_batt
            - wh26_batt
            - wh25_batt
            - wh24_batt
            - wh65_batt
            - wh31_ch1_batt
            - wh31_ch2_batt
            - wh31_ch3_batt
            - wh31_ch4_batt
            - wh31_ch5_batt
            - wh31_ch6_batt
            - wh31_ch7_batt
            - wh31_ch8_batt
            - wh35_ch1_batt
            - wh35_ch2_batt
            - wh35_ch3_batt
            - wh35_ch4_batt
            - wh35_ch5_batt
            - wh35_ch6_batt
            - wh35_ch7_batt
            - wh35_ch8_batt
            - wh41_ch1_batt
            - wh41_ch2_batt
            - wh41_ch3_batt
            - wh41_ch4_batt
            - wh45_batt
            - wh51_ch1_batt
            - wh51_ch2_batt
            - wh51_ch3_batt
            - wh51_ch4_batt
            - wh51_ch5_batt
            - wh51_ch6_batt
            - wh51_ch7_batt
            - wh51_ch8_batt
            - wh51_ch9_batt
            - wh51_ch10_batt
            - wh51_ch11_batt
            - wh51_ch12_batt
            - wh51_ch13_batt
            - wh51_ch14_batt
            - wh51_ch15_batt
            - wh51_ch16_batt
            - wh55_ch1_batt
            - wh55_ch2_batt
            - wh55_ch3_batt
            - wh55_ch4_batt
            - wh57_batt
            - wh68_batt
            - ws80_batt
            # signal level
            - wh40_sig
            - wh26_sig
            - wh25_sig
            - wh24_sig
            - wh65_sig
            - wh31_ch1_sig
            - wh31_ch2_sig
            - wh31_ch3_sig
            - wh31_ch4_sig
            - wh31_ch5_sig
            - wh31_ch6_sig
            - wh31_ch7_sig
            - wh31_ch8_sig
            - wh35_ch1_sig
            - wh35_ch2_sig
            - wh35_ch3_sig
            - wh35_ch4_sig
            - wh35_ch5_sig
            - wh35_ch6_sig
            - wh35_ch7_sig
            - wh35_ch8_sig
            - wh41_ch1_sig
            - wh41_ch2_sig
            - wh41_ch3_sig
            - wh41_ch4_sig
            - wh45_sig
            - wh51_ch1_sig
            - wh51_ch2_sig
            - wh51_ch3_sig
            - wh51_ch4_sig
            - wh51_ch5_sig
            - wh51_ch6_sig
            - wh51_ch7_sig
            - wh51_ch8_sig
            - wh51_ch9_sig
            - wh51_ch10_sig
            - wh51_ch11_sig
            - wh51_ch12_sig
            - wh51_ch13_sig
            - wh51_ch14_sig
            - wh51_ch15_sig
            - wh51_ch16_sig
            - wh55_ch1_sig
            - wh55_ch2_sig
            - wh55_ch3_sig
            - wh55_ch4_sig
            - wh57_sig
            - wh68_sig
            - ws80_sig
            # setting
            - setFirmwareUpgrade
            - setCustomServer
            - setUserPath

item_structs: NONE
    # Definition of item-structure templates for this plugin (enter 'item_structs: NONE', if section should be empty)

#item_attribute_prefixes:
    # Definition of item attributes that only have a common prefix (enter 'item_attribute_prefixes: NONE' or ommit this section, if section should be empty)
    # NOTE: This section should only be used, if really nessesary (e.g. for the stateengine plugin)

plugin_functions: NONE
    # Definition of plugin functions defined by this plugin (enter 'plugin_functions: NONE', if section should be empty)

logic_parameters: NONE
    # Definition of logic parameters defined by this plugin (enter 'logic_parameters: NONE', if section should be empty)
