# Metadata for the plugin
plugin:
    # Global plugin attributes
    type: gateway                   # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Anbindung eines Foshk Wetterstation-Gateway wie bspw. GW1000 mit entsprechender API'
        en: 'Connect to a Foshk weatherstation gateway like GW1000 using their API'
    maintainer: sisamiwe
#    tester:                         # Who tests this plugin?
    state: develop                   # change to ready when done with development
#    keywords: iot xyz
#    support: https://knx-user-forum.de/forum/supportforen/smarthome-py

    version: 1.1.1                  # Plugin version (must match the version specified in __init__.py)
    sh_minversion: 1.9.4            # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
#    py_minversion:                 # minimum Python version to use for this plugin
#    py_maxversion:                 # maximum Python version to use for this plugin (leave empty if latest)
    multi_instance: false           # plugin supports multi instance
    restartable: unknown
    classname: Foshk                # class containing the plugin

parameters:
    Gateway_IP:
        type: ipv4
        mandatory: false
        default: '0.0.0.0'
        description:
            de: 'IP-Adresse des Gateways'
            en: 'IP-Adress of the gateway'

    Gateway_Port:
        type: int
        mandatory: false
        default: 45000
        description:
            de: 'UDP Port des Gateways'
            en: 'UDP Port of the Gateway'

    Gateway_Poll_Cycle:
        type: int
        mandatory: false
        default: 20
        valid_min: 16
        valid_max: 600
        description:
            de: 'Zyklus, in dem die Daten via API abgerufen werden'
            en: 'Cycle in which the data will be pulled via API'

    FW_Update_Check_Cycle:
        type: int
        mandatory: false
        default: 0
        valid_min: 0
        valid_max: 90
        description:
            de: 'Interval in Tagen, in dem nach neuer Firmware gesucht wird. 0 bedeutet aus.'
            en: 'Cycle in days in which a check for newer firmware will be performed. 0 means no periodical check'

    Battery_Warning:
        type: bool
        mandatory: false
        default: true
        description:
            de: 'Erzeugt ein separates Datenfeld für eine Batteriewarnung.'
            en: 'Creates a separate Data field für battery warning'

    Sensor_Warning:
        type: bool
        mandatory: false
        default: true
        description:
            de: 'Erzeugt ein separates Datenfeld für eine Sensorwarnung.'
            en: 'Creates a separate Data field für sensor warning'
            
    Ecowitt_Data_Cycle:
        type: int
        mandatory: False
        default: 20
        valid_min: 0
        valid_max: 600
        description:
            de: 'Intervall, in dem das Gateway die Daten bereitstellt, bzw. hochlädt; (Wert 0: Aus, ECOWITT Daten werden nicht geladen; Wert 1-16: Datenzyklus 16s;  Wert >16 :  Datenzyklus s)'
            en: 'Interval the gateway provides the data'

item_attributes:
    foshk_attibute:
        type: str
        description:
            de: 'Datenattribut des Foshk-Gerätes'
            en: 'Data attribute of Foshk device'
        valid_list:
            # Gateway
            - gateway_model
            - frequency
            - datetime_utc
            - runtime
            - sensor_warning
            - battery_warning
            - storm_warning
            - thunderstorm_warning
            - weatherstation_warning
            - firmware_version
            - firmware_update_available
            - firmware_update_text
            - set_reset
            - set_reboot
            - set_firmware_upgrade
            - set_custom_server
            - set_user_path
            # indoor
            - intemp                        # Innentemperatur
            - inhumid                       # Innenluftfeuchtigkeit
            - absbarometer                  # absoluter Luftdruck
            - relbarometer                  # relativer Luftdruck
            - indewpt                       # Taupunkt
            - inabshum                      # absolute Luftfeuchte
            # WH65 / WH24
            - outtemp                       # Außentemperatur
            - outhumid                      # Außenluftfeuchtigkeit
            - solarradiation                # Sonneneinstrahlung
            - uvi                           # UV Index
            - light                         # Helligkeit
            - cloud_ceiling                 # Wolkenhöhe basierend auf Temp und Dewpoint *Berechnung im Plugin
            - heatindex                     # to be implemented
            - outdewpt                      # Taupunkt außen
            - outfrostpt                    # Frostpunkt außen
            - outabshum                     # absolute Luftfeuchte
            - feels_like                    # gefühlte Außentemperatur
            - wh24_batt                     # Batteriewarnung Wetterstation WH24
            - wh65_batt                     # Batteriewarnung Wetterstation WH65
            - wh24_sig                      # Signalstärke Wetterstation WH24
            - wh65_sig                      # Signalstärke Wetterstation WH24
            # rain
            - rain
            - rainevent                     # kumulierte Regenmenge in mm des aktuellen Regenevents
            - rainrate                      # Regenmenge pro Zeit in mm/h des aktuellen Regenevents
            - rainhour                      # kumulierte Regenmenge der aktuellen Stunde
            - rainday                       # kumulierte Regenmenge des aktuellen Tages
            - rainweek                      # kumulierte Regenmenge der aktuellen Woche
            - rainmonth                     # kumulierte Regenmenge des aktuellen Monats
            - rainyear                      # kumulierte Regenmenge des aktuellen Jahres
            - raintotals                    # kumulierte Regenmenge seit Inbetriebnahme bzw. Reset
            # wind
            - winddir                       # Windrichtung in °
            - windspeed                     # Windgeschwindigkeit in m/s
            - gustspeed                     # Windböengeschwindigkeit in m/s
            - winddaymax                    # max. Windböengeschwindigkeit des Tages in m/s
            - winddir_text                  # Windrichtung als Richtungstext *Berechnung im Plugin
            - windspeed_bft                 # Windgeschwindingkeit auf der Beauford Skala *Berechnung im Plugin
            - windspeed_bft_text            # Windgeschwindingkeit auf der Beauford Skala als Text *Berechnung im Plugin
            - weather_text                  # Beschreibung des aktuellen Wetters als Text *Berechnung im Plugin
            - windspeed_avg10m              # Durchschnittliche Windgeschwindigkeit der letzten 10min *Berechnung im Plugin
            - winddir_avg10m                # Durchschnittliche Windrichtung der letzten 10min *Berechnung im Plugin
            - gustspeed_avg10m              # Durchschnittliche Windboeen der letzten 10min *Berechnung im Plugin
            # WH31
            - temp1
            - temp2
            - temp3
            - temp4
            - temp5
            - temp6
            - temp7
            - temp8
            - humid1
            - humid2
            - humid3
            - humid4
            - humid5
            - humid6
            - humid7
            - humid8
            - dewpt1
            - dewpt2
            - dewpt3
            - dewpt4
            - dewpt5
            - dewpt6
            - dewpt7
            - dewpt8
            - abshum1
            - abshum2
            - abshum3
            - abshum4
            - abshum5
            - abshum6
            - abshum7
            - abshum8
            - wh31_ch1_batt
            - wh31_ch2_batt
            - wh31_ch3_batt
            - wh31_ch4_batt
            - wh31_ch5_batt
            - wh31_ch6_batt
            - wh31_ch7_batt
            - wh31_ch8_batt
            - wh31_ch1_sig
            - wh31_ch2_sig
            - wh31_ch3_sig
            - wh31_ch4_sig
            - wh31_ch5_sig
            - wh31_ch6_sig
            - wh31_ch7_sig
            - wh31_ch8_sig
            # WH34
            - temp_tf_ch1
            - temp_tf_ch2
            - temp_tf_ch3
            - temp_tf_ch4
            - temp_tf_ch5
            - temp_tf_ch6
            - temp_tf_ch7
            - temp_tf_ch8
            - wh34_ch1_batt
            - wh34_ch2_batt
            - wh34_ch3_batt
            - wh34_ch4_batt
            - wh34_ch5_batt
            - wh34_ch6_batt
            - wh34_ch7_batt
            - wh34_ch8_batt
            - wh34_ch1_sig
            - wh34_ch2_sig
            - wh34_ch3_sig
            - wh34_ch4_sig
            - wh34_ch5_sig
            - wh34_ch6_sig
            - wh34_ch7_sig
            - wh34_ch8_sig
            # WH51
            - soilmoist1
            - soilmoist2
            - soilmoist3
            - soilmoist4
            - soilmoist5
            - soilmoist6
            - soilmoist7
            - soilmoist8
            - soilmoist9
            - soilmoist10
            - soilmoist11
            - soilmoist12
            - soilmoist13
            - soilmoist14
            - soilmoist15
            - soilmoist16
            - wh51_ch1_batt
            - wh51_ch2_batt
            - wh51_ch3_batt
            - wh51_ch4_batt
            - wh51_ch5_batt
            - wh51_ch6_batt
            - wh51_ch7_batt
            - wh51_ch8_batt
            - wh51_ch9_batt
            - wh51_ch10_batt
            - wh51_ch11_batt
            - wh51_ch12_batt
            - wh51_ch13_batt
            - wh51_ch14_batt
            - wh51_ch15_batt
            - wh51_ch16_batt
            - wh51_ch1_sig
            - wh51_ch2_sig
            - wh51_ch3_sig
            - wh51_ch4_sig
            - wh51_ch5_sig
            - wh51_ch6_sig
            - wh51_ch7_sig
            - wh51_ch8_sig
            - wh51_ch9_sig
            - wh51_ch10_sig
            - wh51_ch11_sig
            - wh51_ch12_sig
            - wh51_ch13_sig
            - wh51_ch14_sig
            - wh51_ch15_sig
            - wh51_ch16_sig
            # WH45
            - temp17
            - humid17
            - pm10
            - pm10_24h_avg
            - pm255
            - pm255_24h_avg
            - co2
            - co2_24h_avg
            - wh45_batt
            # WH41 / WH43
            - wh41_ch1_batt
            - wh41_ch2_batt
            - wh41_ch3_batt
            - wh41_ch4_batt
            - wh45_batt
            - wh41_ch1_sig
            - wh41_ch2_sig
            - wh41_ch3_sig
            - wh41_ch4_sig
            - wh45_sig
            # WH55
            - leak1
            - leak2
            - leak3
            - leak4
            - wh55_ch1_batt
            - wh55_ch2_batt
            - wh55_ch3_batt
            - wh55_ch4_batt
            - wh55_ch1_sig
            - wh55_ch2_sig
            - wh55_ch3_sig
            - wh55_ch4_sig
            # WH57
            - lightningdist
            - lightningdettime
            - lightningcount
            - lightning_strike_count
            - wh57_batt
            - wh57_sig
            # WN35 Leaf Wetness Sensor
            - leafwet1
            - leafwet2
            - leafwet3
            - leafwet4
            - leafwet5
            - leafwet6
            - leafwet7
            - leafwet8
            # self calculated keys
            - weather_text

    foshk_datasource:
        type: str
        description:
            de: 'Datenquelle der Werte für Items; API vs. ECOWITT'
            en: 'Data source for item values; API vs. ECOWITT'
        valid_list_ci:
            - api
            - ecowitt            

item_structs:
    gateway:
        gateway_model:
            type: str
            visu_acl: ro
            foshk_attibute: gateway_model

        dateutc:
            type: foo
            visu_acl: ro
            foshk_attibute: datetime_utc

        runtime:
            type: num
            visu_acl: ro
            foshk_attibute: runtime

        frequency:
            type: str
            visu_acl: ro
            foshk_attibute: frequency

        firmware:
            type: str
            visu_acl: ro
            foshk_attibute: firmware_version

            update_available:
                type: bool
                visu_acl: ro
                foshk_attibute: firmware_update_available

            update_text:
                type: list
                visu_acl: ro
                foshk_attibute: firmware_update_text

        weatherstation_warning:
            type: bool
            visu_acl: ro
            foshk_attibute: weatherstation_warning

        sensor_warning:
            type: bool
            visu_acl: ro
            foshk_attibute: sensor_warning

        battery_warning:
            type: bool
            visu_acl: ro
            foshk_attibute: battery_warning

        storm_warning:
            type: bool
            visu_acl: ro
            foshk_attibute: storm_warning

        thunderstorm_warning:
            type: bool
            visu_acl: ro
            foshk_attibute: thunderstorm_warning

        reboot:
            type: bool
            visu_acl: rw
            foshk_attibute: set_reboot

        reset:
            type: bool
            visu_acl: rw
            foshk_attibute: set_reset
    rain:
        type: num
        foshk_attibute: rain

        rate:
            type: num
            foshk_attibute: rainrate
        event:
            type: num
            foshk_attibute: rainevent
        hour:
            type: num
            foshk_attibute: rainhour
        day:
            type: num
            foshk_attibute: rainday
        week:
            type: num
            foshk_attibute: rainweek
        month:
            type: num
            foshk_attibute: rainmonth
        year:
            type: num
            foshk_attibute: rainyear
        total:
            type: num
            foshk_attibute: raintotals
    wind:
        winddir:
            type: num
            foshk_attibute: winddir
            database: yes
        winddir_text:
            type: str
            foshk_attibute: winddir_text
        winddir_avg10m:
            type: num
            foshk_attibute: winddir_avg10m
        windspeedkmh:
            type: num
            foshk_attibute: windspeed
            database: yes
            enforce_updates: on
        windspeed_bft:
            type: num
            foshk_attibute: windspeed_bft
        windspeed_bft_text:
            type: str
            foshk_attibute: windspeed_bft_text
        windspdkmh_avg10m:
            type: num
            foshk_attibute: windspeed_avg10m
        windgustkmh:
            type: num
            foshk_attibute: gustspeed
            database: yes
            enforce_updates: on
        windgustkmh_max10m:
            type: num
            foshk_attibute: gustspeed_avg10m
#        winddaymax:
#            type: num
#            foshk_attibute: winddaymax

item_attribute_prefixes: NONE

plugin_functions:
    firmware_update:
        type: bool
        description:
            de: 'Firmware update'
            en: 'command firmware update'

    reboot:
        type: bool
        description:
            de: 'Reboot'
            en: 'command reboot'

    reset:
        type: bool
        description:
            de: 'Reset'
            en: 'command reset'

    set_usr_path:
        type: foo
        description:
            de: 'Setzen des UserPath für Ecowitt und WU Daten upload'
            en: 'set user path for Ecowitt and WU data upload'
        parameters:
            custom_ecowitt_pathpath:
                type: str
                description:
                    de: 'UserPath für Ecowitt'
                    en: 'User path for Ecowitt'
            custom_wu_path:
                type: str
                description:
                    de: 'UserPath für WU'
                    en: 'User path for WU'

    set_custom_params:
        type: foo
        description:
            de: 'Setzen der Parameter für customized Data Upload'
            en: 'Set paramaters for customized data Upload'
        parameters:
            custom_server_id:
                type: str
                description:
                    de: 'Server ID'
                    en: 'server id'
            custom_password:
                type: str
                description:
                    de: 'Passwort'
                    en: 'password'
            custom_host:
                type: ipv4
                description:
                    de: 'IP Adresse des Servers, auf den die Daten geladen werden sollen'
                    en: 'ip address of the server the data should be uploaded to'
            custom_port:
                type: num
                description:
                    de: 'Port des Servers, auf den die Daten geladen werden sollen'
                    en: 'port address of the server the data should be uploaded to'
            custom_interval:
                type: num
                description:
                    de: 'Zyklus, in dem die Daten auf den Server geladen werden'
                    en: 'Cycle, in which the the data will be uploaded'
                valid_min: 16
                valid_max: 300
            custom_type:
                type: bool
                description:
                    de: 'WU (=True) oder Ecowitt (=False) Protokoll'
                    en: 'WU (=True) or Ecowitt (=False) protocol'
            custom_enabled:
                type: bool
                description:
                    de: 'AN/AUS für das benutzerdefinierte Hochladen der Daten'
                    en: 'ON/OFF of customized data upload'

logic_parameters: NONE
